### PR TITLE
Bigger image with resize option

### PR DESCRIPTION
**Pull request by nathanharper**
I must admit, I'm after some of that sweet Dogecoin bounty!

I added a much bigger doge image, and enabled a "size" query parameter.

You can do "size=300" and it will make the image a 300x300 square, or you can specify it like "300x400".

These were kind of low-hanging fruit but I'd be happy to do more later if the code doesn't look totally awful to you :)

I also added a few installation steps I needed to the readme; I'm not sure if this could be simplified by doing it in a different order, as I'm not super familiar with node/npm.

### CODE REVIEW

**Comment by nathanharper** [comment]
wow. thanks for the tip! makes a lot more sense now. Anyway, I just rebased the commits.

**Comment by jescalan** [comment]
Sweet - could you update the readme actually just to run `npm install` instead? This is the preferred way to do it : )

 lso you do know that you haven't configured git correctly to link with your github account

**Comment by nathanharper** [comment]
D'oh... nice catch on the github linkup.

Want me to squash this last update into the general readme commit?

**Comment by jescalan** [comment]
Yeah I mean in general the best commit structure would be something like this:
- Add a bigger doge image
- Update readme

but it's going to take a bit of work to tease your commits apart so that they look like this. But at the moment there are two spots where you commit something then undo it in a later commit (readme updates and addition of the doge image) - if they were to be organized as above, it would cut down on confusion a little when reading through the commit logs : )

**Comment by nathanharper** [comment]
Alright, there's still a little bit of readme stuff in ecc0118 but I did my best squash. Honestly, thanks for the git help, I'm still finding my way around apparently.

**Comment by jescalan** [comment]
Looks a bunch better. Me and/or @samccone will pull this down and test when we have a chance. If you can get that readme stuff out of the first commit you get extra champion points. It's just a matter of resetting and carefully re-adding only the files you want to commit. And no worries on the git stuff, it really is a never-ending journey hah

**Comment by nathanharper** [comment]
Okay... `git rebase -i` is pretty sweet. I think I'm finally completely won over from svn. Commits should be nice and tidy now and I tweaked it a bit for safety. Also the 'x' in the size parameter is case insensitive now :P Enjoy!

**Comment by samccone** [comment]
@nathanharper just leave your dogecoin wallet address for the payout :+1:

**Comment by nathanharper** [comment]
woop, thanks!

DKov2672nYDC1LKenjbyCsHf39NMqZRXbB

**Comment by jescalan** [comment]
This looks fantastic @nathanharper - nice work on that rebase. Well deserved dogecoins.

**Comment by samccone** [comment]
just need to test this out when i get some :clock1:

**Comment by nathanharper** [comment]
Er, yeah, so I was sitting on some stuff in a branch and I decided to just fold it all into this pull request. Not really expecting a bounty for the index page update as it falls into the "better than nothing, but not by much" category. If you'd rather handle in separate requests, I can reset a few commits. Cheers!

**Comment by samccone** [comment]
ah yeah can you rip the other stuff out of this PR and please rebase off of master @nathanharper

**Comment by nathanharper** [comment]
Thanks @samccone , fixed.

**Comment by samccone** [comment]
Gotta rebase still

**Comment by nathanharper** [comment]
Sorry, not sure I understand. What needs to be fixed?

**Comment by nathanharper** [comment]
Oh nvm, you mean off your master, right? Workin on it...

**Comment by nathanharper** [comment]
Ok, @samccone , I did a `git pull --rebase` from the latest master and pushed my updates, should be up to date. Lemme know if you need anything else.

**Comment by samccone** [comment]
@nathanharper just leave your doge coin address for your sweet coins!

**Comment by samccone** [comment]
err nm @nathanharper all sent!

**Comment by nathanharper** [comment]
Yay! Thanks!

**Pull request merged**
