### PR TITLE
Add dogesled.

### LINKED ISSUE #14: add bobsled doge image
something like this
http://www.cbc.ca/strombo/content/images/doge-cool-runnings.jpg

dogesay.com/?image=bobsled

---

doge bounty 500

### PR DESCRIPTION
**Pull request by markalfred**
fixes #14 
`?image=bobsled`

image

`D7ozVVxKwhWjcF9r6QVJ7dCr69PpMJ1aEx`

### CODE REVIEW

**Comment by samccone** [comment]
@markalfred rebase plz

**Comment by markalfred** [comment]
:heavy_dollar_sign::heavy_dollar_sign::heavy_dollar_sign:

**Comment by markalfred** [comment]
:dancers:

**Comment by samccone** [comment]
ø______________________ø

**Pull request merged**
