### PR TITLE
LRU caching

### PR DESCRIPTION
**Pull request by nathanharper**
Hey, so I implemented some simple LRU caching and also cleaned up a little. Image names/dimensions are in the config now, and static routing should be fixed.

### CODE REVIEW

**Comment by samccone** [comment]
! thanks @nathanharper will look this over

**Comment by samccone** [comment]
1 comment @nathanharper then we can ship!

thanks for the greaaaat PR!

**Comment by nathanharper** [comment]
Yeah, no problem! I've been trying to commit to contributing more to some open source projects I use, so i'd be happy to help out more squashing some bugs in roots.

**Comment by jescalan** [comment]
:+1: @nathanharper

**Comment by jescalan** [comment]
:tada:

**Pull request merged**
